// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XcavateProfileApi.Data;

#nullable disable

namespace XcavateProfileApi.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    partial class ProfileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XcavateProfile.Client.Profile", b =>
                {
                    b.Property<string>("Ss58Address")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "ss58address");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "bio");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "nickname");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "profilePicture");

                    b.Property<string>("X25519Key")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "x25519Key");

                    b.HasKey("Ss58Address");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
